# Generated by Django 5.0.1 on 2025-10-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_web', '0002_remove_ragconfiguration_text_extractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragconfiguration',
            name='is_validation',
            field=models.BooleanField(default=False, verbose_name='검증용 구성'),
        ),
    ]
