# Generated by Django 5.0.1 on 2025-10-15 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_web', '0003_ragconfiguration_is_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('region', models.CharField(blank=True, choices=[('경남', '경남'), ('경북', '경북'), ('대구', '대구'), ('부산', '부산'), ('전국', '전국'), ('전남', '전남'), ('전북', '전북')], max_length=50, verbose_name='사는 지역')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
            },
        ),
    ]
