# Generated by Django 5.0.1 on 2025-10-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_web', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시'), ('인천광역시', '인천광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원특별자치도', '강원특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전북특별자치도', '전북특별자치도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도')], max_length=50, verbose_name='사는 지역'),
        ),
    ]
