# Generated by Django 5.0.1 on 2025-10-14 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('title', models.CharField(default='새 대화', max_length=200, verbose_name='대화 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '챗봇'), ('system', '시스템')], max_length=20, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('retrieved_docs', models.JSONField(blank=True, null=True, verbose_name='검색된 문서')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='응답 시간(초)')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='사용된 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_web.chatsession')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='구성 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('text_extractor', models.CharField(choices=[('PyPDF2', 'PyPDF2'), ('pdfplumber', 'PDF Plumber'), ('PyMuPDF', 'PyMuPDF (Fitz)'), ('pdfminer', 'PDFMiner'), ('unstructured', 'Unstructured'), ('olefile', 'OleFile (HWP)'), ('hwpx', 'HWPX'), ('advanced_hwp', 'Advanced HWP')], default='advanced_hwp', max_length=50, verbose_name='텍스트 추출기')),
                ('chunking_strategy', models.CharField(choices=[('fixed_size', 'Fixed Size'), ('sentence', 'Sentence-based'), ('paragraph', 'Paragraph-based'), ('semantic', 'Semantic'), ('recursive', 'Recursive Character')], default='recursive', max_length=50, verbose_name='청킹 전략')),
                ('chunk_size', models.IntegerField(default=1000, verbose_name='청크 크기')),
                ('chunk_overlap', models.IntegerField(default=200, verbose_name='청크 오버랩')),
                ('embedding_model', models.CharField(choices=[('openai', 'OpenAI text-embedding-ada-002'), ('sentence-transformers/all-MiniLM-L6-v2', 'MiniLM-L6-v2 (영어)'), ('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', 'Multilingual MiniLM'), ('jhgan/ko-sroberta-multitask', 'KoSRoBERTa'), ('BM-K/KoSimCSE-roberta', 'KoSimCSE')], default='jhgan/ko-sroberta-multitask', max_length=100, verbose_name='임베딩 모델')),
                ('retrieval_strategy', models.CharField(choices=[('similarity', 'Similarity Search'), ('mmr', 'MMR (Maximal Marginal Relevance)'), ('bm25', 'BM25'), ('ensemble', 'Ensemble (Hybrid)')], default='similarity', max_length=50, verbose_name='검색 전략')),
                ('top_k', models.IntegerField(default=5, verbose_name='검색 결과 개수')),
                ('collection_name', models.CharField(max_length=100, unique=True, verbose_name='컬렉션 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('document_count', models.IntegerField(default=0, verbose_name='문서 수')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('build_status', models.CharField(choices=[('pending', '대기 중'), ('building', '구축 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='구축 상태')),
                ('build_started_at', models.DateTimeField(blank=True, null=True, verbose_name='구축 시작 시간')),
                ('build_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='구축 완료 시간')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG 구성',
                'verbose_name_plural': 'RAG 구성들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rag_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_web.ragconfiguration'),
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], verbose_name='평점')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot_web.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 피드백',
                'verbose_name_plural': '사용자 피드백들',
                'ordering': ['-created_at'],
            },
        ),
    ]
