# Generated by Django 5.0.1 on 2025-10-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragconfiguration',
            name='text_extractor',
        ),
        migrations.AddField(
            model_name='ragconfiguration',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='오류 메시지'),
        ),
        migrations.AddField(
            model_name='ragconfiguration',
            name='hwp_extractor',
            field=models.CharField(choices=[('olefile', 'OleFile (HWP 3.0-5.0)'), ('hwpx', 'HWPX (HWP 2014+)'), ('advanced_hwp', 'Advanced HWP (권장)')], default='advanced_hwp', max_length=50, verbose_name='HWP 추출기'),
        ),
        migrations.AddField(
            model_name='ragconfiguration',
            name='pdf_extractor',
            field=models.CharField(choices=[('PyPDF2', 'PyPDF2'), ('pdfplumber', 'PDF Plumber'), ('PyMuPDF', 'PyMuPDF (Fitz)'), ('pdfminer', 'PDFMiner'), ('unstructured', 'Unstructured')], default='pdfplumber', max_length=50, verbose_name='PDF 추출기'),
        ),
        migrations.AddField(
            model_name='ragconfiguration',
            name='total_chunks',
            field=models.IntegerField(default=0, verbose_name='총 청크 수'),
        ),
        migrations.AddField(
            model_name='ragconfiguration',
            name='total_documents',
            field=models.IntegerField(default=0, verbose_name='총 문서 수'),
        ),
        migrations.AddField(
            model_name='ragconfiguration',
            name='use_ocr',
            field=models.BooleanField(default=True, verbose_name='OCR 사용 (PDF 실패 시)'),
        ),
    ]
