# Generated by Django 5.0.1 on 2025-10-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_web', '0005_alter_userprofile_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderlyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='정책명')),
                ('provider', models.CharField(max_length=100, verbose_name='제공기관')),
                ('region', models.CharField(blank=True, choices=[('전국', '전국'), ('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시'), ('인천광역시', '인천광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원특별자치도', '강원특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전북특별자치도', '전북특별자치도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도')], default='전국', max_length=50, verbose_name='지역')),
                ('policy_url', models.URLField(blank=True, verbose_name='정책 링크')),
                ('description', models.TextField(blank=True, verbose_name='정책 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '노년 복지 정책',
                'verbose_name_plural': '노년 복지 정책들',
                'ordering': ['region', 'title'],
            },
        ),
    ]
