# Generated by Django 5.0.1 on 2025-10-13 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='정책명')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('description', models.TextField(verbose_name='설명')),
                ('target', models.CharField(max_length=200, verbose_name='대상')),
                ('url', models.URLField(blank=True, verbose_name='관련 링크')),
                ('file_name', models.CharField(blank=True, max_length=500, verbose_name='원본 파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '정책',
                'verbose_name_plural': '정책',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('relevance_score', models.FloatField(blank=True, null=True, verbose_name='관련성 점수')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='정확성 점수')),
                ('completeness_score', models.FloatField(blank=True, null=True, verbose_name='완전성 점수')),
                ('overall_score', models.FloatField(blank=True, null=True, verbose_name='종합 점수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 이력',
                'verbose_name_plural': '채팅 이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('기타', '기타')], max_length=10, null=True, verbose_name='성별')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='거주지역')),
                ('disability', models.BooleanField(default=False, verbose_name='장애 여부')),
                ('veteran', models.BooleanField(default=False, verbose_name='보훈 대상 여부')),
                ('low_income', models.BooleanField(default=False, verbose_name='저소득층 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
