# Generated by Django 5.0.1 on 2025-10-13 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='문서 제목')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='파일')),
                ('file_type', models.CharField(max_length=10, verbose_name='파일 형식')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('extracted_text', models.TextField(blank=True, verbose_name='추출된 텍스트')),
                ('is_synced', models.BooleanField(default=False, verbose_name='ChromaDB 동기화 여부')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
                'ordering': ['-created_at'],
            },
        ),
    ]
