# Generated by Django 4.2.7 on 2025-10-19 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='openai', max_length=50, verbose_name='프로바이더')),
                ('api_endpoint', models.CharField(blank=True, max_length=200, verbose_name='엔드포인트')),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_summary', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API 사용 로그',
                'verbose_name_plural': 'API 사용 로그들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '챗봇'), ('system', '시스템')], max_length=20, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('retrieved_docs', models.JSONField(blank=True, null=True, verbose_name='검색된 문서')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='응답 시간(초)')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='사용된 토큰')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('title', models.CharField(default='새 대화', max_length=200, verbose_name='대화 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션들',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ElderlyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='정책명')),
                ('provider', models.CharField(max_length=100, verbose_name='제공기관')),
                ('region', models.CharField(blank=True, choices=[('전국', '전국'), ('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('대구광역시', '대구광역시'), ('인천광역시', '인천광역시'), ('광주광역시', '광주광역시'), ('대전광역시', '대전광역시'), ('울산광역시', '울산광역시'), ('세종특별자치시', '세종특별자치시'), ('경기도', '경기도'), ('강원특별자치도', '강원특별자치도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전북특별자치도', '전북특별자치도'), ('전라남도', '전라남도'), ('경상북도', '경상북도'), ('경상남도', '경상남도'), ('제주특별자치도', '제주특별자치도')], default='전국', max_length=50, verbose_name='지역')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='분야')),
                ('target', models.TextField(blank=True, verbose_name='대상')),
                ('benefits', models.TextField(blank=True, verbose_name='혜택내용')),
                ('how_to_apply', models.TextField(blank=True, verbose_name='신청방법')),
                ('required_docs', models.TextField(blank=True, verbose_name='구비서류')),
                ('contact', models.TextField(blank=True, verbose_name='문의처')),
                ('policy_url', models.URLField(blank=True, verbose_name='정책 링크')),
                ('description', models.TextField(blank=True, verbose_name='정책 설명')),
                ('source_file', models.CharField(blank=True, max_length=500, verbose_name='출처 파일')),
                ('extracted_text', models.TextField(blank=True, verbose_name='추출된 원문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '노년 복지 정책',
                'verbose_name_plural': '노년 복지 정책들',
                'ordering': ['region', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, choices=[('남성', '남성'), ('여성', '여성'), ('기타', '기타')], max_length=10, null=True, verbose_name='성별')),
                ('region', models.CharField(blank=True, choices=[('경남', '경남'), ('경북', '경북'), ('대구', '대구'), ('부산', '부산'), ('전국', '전국'), ('전남', '전남'), ('전북', '전북'), ('서울', '서울'), ('인천', '인천'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('세종', '세종'), ('광주', '광주'), ('제주', '제주')], max_length=50, verbose_name='사는 지역')),
                ('disability', models.BooleanField(default=False, verbose_name='장애 여부')),
                ('veteran', models.BooleanField(default=False, verbose_name='보훈 대상 여부')),
                ('low_income', models.BooleanField(default=False, verbose_name='저소득층 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], verbose_name='평점')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot_web.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 피드백',
                'verbose_name_plural': '사용자 피드백들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrieverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='검색 질의')),
                ('retrieved', models.JSONField(blank=True, default=list, verbose_name='검색 결과 정보(문서 id, score 등)')),
                ('user_region', models.CharField(blank=True, max_length=100, verbose_name='사용자 지역')),
                ('elapsed_ms', models.IntegerField(blank=True, null=True, verbose_name='소요 시간(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retriever_logs', to='chatbot_web.chatsession')),
            ],
            options={
                'verbose_name': '리트리버 로그',
                'verbose_name_plural': '리트리버 로그들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='구성 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('pdf_extractor', models.CharField(choices=[('PyPDF2', 'PyPDF2'), ('pdfplumber', 'PDF Plumber'), ('PyMuPDF', 'PyMuPDF (Fitz)'), ('pdfminer', 'PDFMiner'), ('unstructured', 'Unstructured')], default='pdfplumber', max_length=50, verbose_name='PDF 추출기')),
                ('hwp_extractor', models.CharField(choices=[('olefile', 'OleFile (HWP 3.0-5.0)'), ('hwpx', 'HWPX (HWP 2014+)'), ('advanced_hwp', 'Advanced HWP (권장)')], default='advanced_hwp', max_length=50, verbose_name='HWP 추출기')),
                ('use_ocr', models.BooleanField(default=True, verbose_name='OCR 사용 (PDF 실패 시)')),
                ('chunking_strategy', models.CharField(choices=[('fixed_size', 'Fixed Size'), ('sentence', 'Sentence-based'), ('paragraph', 'Paragraph-based'), ('semantic', 'Semantic'), ('recursive', 'Recursive Character')], default='recursive', max_length=50, verbose_name='청킹 전략')),
                ('chunk_size', models.IntegerField(default=1000, verbose_name='청크 크기')),
                ('chunk_overlap', models.IntegerField(default=200, verbose_name='청크 오버랩')),
                ('embedding_model', models.CharField(choices=[('openai', 'OpenAI text-embedding-ada-002'), ('sentence-transformers/all-MiniLM-L6-v2', 'MiniLM-L6-v2 (영어)'), ('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', 'Multilingual MiniLM'), ('jhgan/ko-sroberta-multitask', 'KoSRoBERTa'), ('BM-K/KoSimCSE-roberta', 'KoSimCSE')], default='jhgan/ko-sroberta-multitask', max_length=100, verbose_name='임베딩 모델')),
                ('retrieval_strategy', models.CharField(choices=[('similarity', 'Similarity Search'), ('mmr', 'MMR (Maximal Marginal Relevance)'), ('bm25', 'BM25'), ('ensemble', 'Ensemble (Hybrid)')], default='similarity', max_length=50, verbose_name='검색 전략')),
                ('top_k', models.IntegerField(default=5, verbose_name='검색 결과 개수')),
                ('collection_name', models.CharField(max_length=100, unique=True, verbose_name='컬렉션 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_validation', models.BooleanField(default=False, verbose_name='검증용 구성')),
                ('document_count', models.IntegerField(default=0, verbose_name='문서 수')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('build_status', models.CharField(choices=[('pending', '대기 중'), ('building', '구축 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='구축 상태')),
                ('build_started_at', models.DateTimeField(blank=True, null=True, verbose_name='구축 시작 시간')),
                ('build_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='구축 완료 시간')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('total_documents', models.IntegerField(default=0, verbose_name='총 문서 수')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='총 청크 수')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RAG 구성',
                'verbose_name_plural': 'RAG 구성들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rag_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot_web.ragconfiguration'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_web.chatsession'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(blank=True, max_length=1000, verbose_name='원본 파일 경로')),
                ('chunk_index', models.IntegerField(verbose_name='청크 인덱스')),
                ('text', models.TextField(verbose_name='청크 텍스트')),
                ('embedding', models.BinaryField(blank=True, null=True, verbose_name='임베딩(바이너리) -- 선택적 저장')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='chatbot_web.elderlypolicy')),
            ],
            options={
                'verbose_name': '문서 청크',
                'verbose_name_plural': '문서 청크들',
                'indexes': [models.Index(fields=['chunk_index'], name='chatbot_web_chunk_i_b20caf_idx')],
            },
        ),
    ]
