# Generated by Django 4.2.7 on 2025-10-20 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot_web', '0002_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.BigIntegerField(unique=True, verbose_name='카카오 ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='닉네임')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('profile_image', models.URLField(blank=True, null=True, verbose_name='프로필 이미지')),
                ('thumbnail_image', models.URLField(blank=True, null=True, verbose_name='썸네일 이미지')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='리프레시 토큰')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='토큰 만료 시각')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], max_length=10, null=True, verbose_name='성별')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='지역')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인')),
            ],
            options={
                'verbose_name': '카카오 사용자',
                'verbose_name_plural': '카카오 사용자들',
                'db_table': 'kakao_users',
            },
        ),
        migrations.CreateModel(
            name='SessionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='별점 (0.5 단위)')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='chatbot_web.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '세션 평가',
                'verbose_name_plural': '세션 평가들',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
